// Documentation of everything built, as data — rendered by the developer console's Docs tab (src/app/dev/page.tsx).
// Written from the code (round 3). Keep it next to the code it describes: when you add a screen, API route,
// migration, env var or cron job, add a line here. `unsure` marks anything not verified end to end.
// Agents are documented in src/lib/agents/catalog.ts (the console shows both).

export type DocRole = 'owner' | 'supervisor' | 'worker' | 'developer';

export interface DocFeature {
  id: string;
  area: 'Home' | 'Stock' | 'Production' | 'Photo reading' | 'Sales' | 'Money' | 'Reports' | 'Firm & team' | 'Access & sign-in' | 'Assistant' | 'Developer';
  title: string;
  roles: DocRole[];
  where: string; // how to get there in the app
  what: string; // what it does, plain words
  data: string; // where the data comes from / goes to
  rules: string[];
  apis: string[];
  code: string[];
  unsure?: string;
}

export const FEATURES: DocFeature[] = [
  // ---------------- Home ----------------
  {
    id: 'overview', area: 'Home', title: 'Overview (owner home)', roles: ['owner'], where: 'Menu → Overview',
    what: 'What needs the owner now ("Needs your attention"), what is happening right now (received / dispatched today, open job cards), stock flow over a chosen period with demand by quality, sections today, and time saved by photo capture.',
    data: 'Stock ledger (stock_movements, lots), job cards, agent suggestions, time-saved figures (/api/value).',
    rules: ['"Today" is the database date, so it matches every other today-figure.', 'No stock value (₹) card — removed at the owner\'s request.'],
    apis: ['GET /api/overview', 'GET /api/stock', 'GET /api/stock/flow', 'GET /api/value', 'GET /api/agents/suggestions'],
    code: ['src/components/screens/Overview.tsx', 'src/components/screens/Today.tsx'],
    unsure: 'Being redesigned in round 3 (engineer D) — layout details may differ.',
  },
  {
    id: 'floor', area: 'Home', title: 'Floor today (supervisor home)', roles: ['supervisor'], where: 'Menu → Floor today',
    what: 'The supervisor\'s sections today: their workers, allotted vs done, idle alerts, photo reads to review, and agent cards they are allowed to see (meters only).',
    data: 'Workers, job cards, CCTV activity, capture events, agent suggestions (owner-only ones removed).',
    rules: ['A supervisor only sees the sections the owner gave them.', 'Never any ₹.'],
    apis: ['GET /api/workers', 'GET /api/job-cards', 'GET /api/agents/suggestions'],
    code: ['src/components/screens/Floor.tsx'],
  },
  {
    id: 'attention', area: 'Home', title: 'Bell → "Needs your attention"', roles: ['owner', 'supervisor'], where: 'Bell icon in the top bar (desktop drawer, phone sheet)',
    what: 'Two tabs side by side: Alerts (floor items + agent cards with their button) and Review queue (photo reads waiting for a check). The badge shows the total.',
    data: 'Floor items are worked out in the browser from loaded data; agent cards come from agent_suggestions.',
    rules: ['Workers get no alerts.', 'Supervisors never get money cards (owner_only).', 'Each card: what happened (title), why it matters (detail), what the button will do (hint line).', 'Dismissing a card keeps it quiet for its kind\'s quiet days (see Agents).'],
    apis: ['GET /api/agents/suggestions', 'POST /api/agents/suggestions'],
    code: ['src/components/AgentInbox.tsx', 'src/components/Shell.tsx'],
  },
  {
    id: 'search', area: 'Home', title: 'Global search', roles: ['owner', 'supervisor'], where: 'Search box in the top bar',
    what: 'Type a lot no., order no., party, challan or name; results are grouped and each opens the item (deep links such as #order=ID, #ledger=…, #firm=parties&party=ID).',
    data: 'Lots, orders, inquiries, dispatches, parties, people — only what the role may see.',
    rules: ['Supervisors never get ₹; workers get no results.'],
    apis: ['GET /api/search', 'GET /api/search/lot', 'GET /api/lots/search'],
    code: ['src/app/api/search/route.ts'],
    unsure: 'Built in round 3 by engineer B; screen details not re-read for these docs.',
  },
  // ---------------- Stock ----------------
  {
    id: 'ledger', area: 'Stock', title: 'Stock ledger — Movements and Lots & balance', roles: ['owner'], where: 'Menu → Stock ledger',
    what: 'Every IN / OUT entry (newest first) with search and filters (direction, quality, design, lot, party, date range), a count of matching rows and "load more"; and every lot with its balance and location.',
    data: 'stock_movements (+ lots, lot_locations). Keyset-paged on the server.',
    rules: [
      'Lot balance = total IN − total OUT. Meters > 0. OUT more than the balance is refused.', 'Free meters = balance − meters kept aside (reserved) for orders.', 'SR no. and pieces (taka) are shown on every row.', 'Supervisors see stock for their section lots only (no ledger screen).',
      'Register fields (migration 013): IN rows show taka, %, location code ("Loc 212"), mill · weaver and what S-1…S-10 took out before the import; OUT rows show bill no., L, billed meters (NQTY), LOT S (tooltip = our guess of the code, docs/AMBIGUOUS.md §1) and the linked SR ("↳102" in the SR column).',
      '"Opening adjustment (register)" rows (kind = adjustment, Dir "ADJ") are muted: an OUT that makes an imported lot\'s balance equal the register\'s STOCK. Counted in balances, not in dispatched / flow figures, not editable.',
      'Search also finds bill no., location code, linked SR and LOT S (stock_movements.search_doc). Excel export has the register columns too (Kind, Linked SR, %, Location code, L, Billed Mts, LOT S, S-1…S-10).',
    ],
    apis: ['GET /api/stock/ledger', 'GET /api/stock', 'GET /api/lots/search'],
    code: ['src/components/screens/Owner.tsx', 'src/components/screens/StockLedger.tsx', 'src/lib/ledger-query.ts', 'src/lib/useLedger.ts'],
    unsure: 'GET /api/lots/search is being added in round 3 (engineer A).',
  },
  {
    id: 'manual-entry', area: 'Stock', title: 'Manual stock entry (IN / OUT)', roles: ['owner'], where: 'Stock ledger → Add entry',
    what: 'Type an incoming lot (grey / finished meters, mill, weaver, challan, quality, design, location) or an outgoing entry (lot, meters, party, challan).',
    data: 'Writes stock_movements (+ lots for a new lot, lot_locations).',
    rules: [
      'SR no. (register serial) is pre-filled with last + 1 for that direction and editable; a number already used in the same direction is refused with the next free number.',
      'Pieces (taka): optional whole number.',
      'OUT needs a party (the client receiving the goods).',
      '"More fields" (collapsed, optional): IN → % and location code as in the Incoming register; OUT → L, NQTY (billed meters) and LOT S as in the sales register. Saved as data; they never change stock.',
      'Location on arrival (required): market + shop no. (+ pipe no.) → "LM 245 · Pipe 3", picked with the market location picker. Godown / Shop / Floor are not offered.',
      'Every OUT runs the Dispatch agent hook: it is counted against an order by itself only when that lot was kept aside for the order; otherwise, if the party has an open order of that quality, the owner gets a card to count it (or say "Not for an order"). Reservations no longer covered by stock shrink.',
    ],
    apis: ['POST /api/stock', 'GET /api/stock/next-sr'],
    code: ['src/components/screens/Shared.tsx', 'src/components/MarketLocationPicker.tsx', 'src/lib/ledger.ts', 'src/lib/location.ts'],
  },
  {
    id: 'ledger-edit', area: 'Stock', title: 'Ledger edit mode (like a spreadsheet)', roles: ['owner'], where: 'Stock ledger → View / Edit switch',
    what: 'Cells become inputs in place. Enter / ↓ next row, ↑ previous, Tab / Shift+Tab next / previous cell, Esc undoes the cell. Changed cells are highlighted; a bar shows the count with Save and Discard. Leaving with unsaved changes asks first.',
    data: 'PATCH /api/stock/edit; every saved change is written to ledger_edits (who, when, before → after).',
    rules: ['Movements: SR no., pieces, challan / bill no., mill / weaver / % / location code (IN), party / L / NQTY / LOT S (OUT), quality and design (these change every row of the lot). Opening adjustments are read-only.', 'Lots: quality, design, grade, status.', 'Meters, direction, lot no., date and location are not editable here.', 'All-or-nothing: if any change is invalid nothing is saved and the bad cell is shown.', 'Supervisors never see edit mode.'],
    apis: ['PATCH /api/stock/edit', 'GET /api/stock/edit'],
    code: ['src/components/screens/StockEdit.tsx', 'src/lib/ledger-edit.ts'],
  },
  {
    id: 'import', area: 'Stock', title: 'Excel import and export', roles: ['owner'], where: 'Stock ledger → Import / Export',
    what: 'Import one of three formats, told apart by the heading row: (a) the firm\'s Incoming register (DATE, SRNO, LOT NO, MTR, TAKA, %, LOCATION, MILL, WEAVER, S-1…S-10, STOCK, ITEM), (b) its Outgoing / sales register (DATE, BNO, ITEM, L, LOT, LOT S, QTY, NQTY, SR.NO), (c) the app template. The screen says what it found ("Looks like your Incoming register — 23 lots"), checks columns, then rows, then saves in chunks of 500 with a progress bar. Templates for all three can be downloaded. Export: challans (same filters as the screen) or lot balances as .xlsx.',
    data: 'Writes lots + stock_movements (+ lot_locations). Incoming row → new lot + IN of MTR + (MTR − STOCK) as an "opening adjustment" OUT (kind = adjustment, no party), so the balance = STOCK (E/e → 0). Outgoing row → OUT of QTY on the lot whose IN has sr_no = SR.NO (bill no. → source_doc_id; L → bill_pct; NQTY → billed_meters; LOT S → lot_status_code; SR.NO text → linked_sr; party empty).',
    rules: [
      'Headings are matched loosely: case, spaces, dots, one-letter typos ("LOCTION"), " STOCK", SR.NO / SRNO / SR NO, LOT NO / LOT. Unknown columns are listed and ignored; a missing required column blocks the file.',
      'Errors block saving: bad number / date, missing required value (DATE, SRNO, LOT NO, MTR, ITEM; DATE, BNO, QTY), negative values, STOCK above MTR, the same SRNO twice in the file.',
      'Warnings that skip the row (it can\'t be placed): two lots in one row ("172+173", SR "146+204"), SR.NO not in the app (and lot not found), SR.NO pointing at a different lot no., no SR.NO and the lot no. missing or not unique, empty bill rows (only DATE + BNO), not enough stock, incoming SRNO already used by another lot. The owner chooses "Import N, skip M"; skipped rows download as "Rows to fix" (.xlsx, same columns + reason).',
      'Warnings that only inform (row saved): ITEM differs from the lot\'s quality, STOCK disagrees with MTR − S-1…S-10 (STOCK is used), NQTY ≠ QTY × L ÷ 100, unknown LOT S code, date in the future, lot no. already used (saved as "<LOT NO>-SR<SRNO>").',
      'Lot key: the register\'s LOT NO; when that number is already a lot, "<LOT NO>-SR<SRNO>" (lots.reg_lot_no keeps the register\'s number). Sales find lots by SR.NO first, by lot no. only when SR.NO is blank and exactly one lot has it.',
      'No duplicates on re-import: app-template rows use import_ref "<file hash>:<excel row>"; register rows use a hash of the row\'s identity (incoming: SRNO + LOT NO + MTR; sales: date + bill + lot + QTY + SR.NO, + nth identical row), so a re-saved copy of the file is recognised too. The opening adjustment has the same ref + "a".',
      `Up to 20,000 rows per file. Chunks of 500 rows, one transaction each (≈10 k incoming lots in ~100 s locally).`,
      'Formulas are read by their saved result; a formula with no saved result counts as empty (STOCK is then MTR − S-1…S-10).',
      'App template Location (IN): "LM 245 · Pipe 3", "LM 245 3", "LM 245" or "Landmark 245 3" → stored as "LM 245 · Pipe 3" (dropdown lists the market codes). Godown / Shop / Floor / Dispatched are refused with a message; a new shop no. is listed in the check notes and added to the market on import. Incoming-register lots get no app location (LOCATION code kept as loc_code; finished lots → Dispatched).',
      'Open questions about the registers (LOT S, L, %, location codes, mills, combined lots, …): docs/AMBIGUOUS.md — summarised under "Open questions" in this tab.',
    ],
    apis: ['POST /api/stock/import', 'POST /api/stock/import/commit', 'POST /api/stock/import/fix', 'GET /api/stock/export'],
    code: ['src/lib/stock-import.ts', 'src/lib/register-import.ts', 'src/lib/registers.ts', 'src/lib/stockImportClient.ts', 'docs/AMBIGUOUS.md'],
  },
  {
    id: 'locations', area: 'Stock', title: 'Markets & lot locations', roles: ['owner', 'supervisor'], where: 'My firm → Markets & locations (owner); Add entry, Move (owner), confirming an incoming photo read (owner, supervisor)',
    what: 'A lot\'s place is a market location: market initials + shop no. + pipe no., e.g. "LM 245 · Pipe 3" (= Landmark, shop 245, pipe 3; the full name shows on hover). One picker everywhere: market buttons ("LM · Landmark"), shop no. from the market\'s list (most used first) or typed, pipe no. typed. Moving a lot records a new location with history. The owner manages markets (name, initials, on / off) and each market\'s shops in My firm.',
    data: 'markets (name, code = initials, active), market_shops (market_id, shop_no, active), lot_locations (history, newest wins; location = label + market_id / shop_no / pipe_no) — migration 014. app_settings.location_presets / .markets are no longer used.',
    rules: [
      'Format "<CODE> <shop> · Pipe <pipe>". Market required (active markets only); shop no. required: digits + optional letter (245, 12A, up to 8 characters); pipe no. optional: whole number 1–999 ("3.5", "abc", "0", "1000" refused: "Pipe no. must be a whole number like 3").',
      'Initials: 1–6 capital letters / digits, unique; names unique (any case). Changing initials does not rewrite labels already on lots (history stays as written).',
      'Shops: owner and supervisors can add one (from the picker, or by typing a new shop no. — it is added when the entry is saved). Only the owner adds / renames markets, changes initials, switches markets off and removes shops (a removed shop is only off the list).',
      'Godown, Shop and Floor are no longer offered. "Floor" is set by job cards, "Dispatched" when a lot is fully sent out — never picked. Old labels (Godown, Shop, RRTM 245 · Pipe 3) stay on old rows and still display.',
      'No location given (photo read, Incoming register import): a new lot has none ("Not recorded"; the Stock agent lists lots with stock but no location), an existing lot stays where it is.',
      'Search: "LM 245" or the market name ("Landmark") finds lots and ledger rows at that market (also under older initials).',
    ],
    apis: ['GET /api/lots/location', 'POST /api/lots/location', 'GET /api/markets', 'POST /api/markets', 'PATCH /api/markets', 'POST /api/markets/shops', 'PATCH /api/markets/shops'],
    code: ['src/lib/location.ts', 'src/lib/markets.ts', 'src/lib/normalize.ts (allowedLocation)', 'src/components/MarketLocationPicker.tsx', 'src/components/screens/MyFirm.tsx', 'scripts/migrations/014_markets.sql'],
  },
  // ---------------- Production ----------------
  {
    id: 'job-cards', area: 'Production', title: 'Job cards and allot work', roles: ['owner', 'supervisor'], where: 'Menu → Job cards; supervisor → Allot work',
    what: 'Create a job card for a lot and allot it to a worker (the lot moves to the floor); close it with meters out — shortage % and worker efficiency are worked out.',
    data: 'job_cards, allotments, efficiency_daily; lot_locations.',
    rules: ['Only the Folding and Packing sections are in use (others kept switched off).', 'Shortage above the firm\'s limit (My firm → Policy) is flagged.', 'A lot goes to "Floor" when a card opens and back to its place before the floor when its last card closes (a lot that had no place stays on Floor until moved).', 'Supervisors: their sections only.'],
    apis: ['GET /api/job-cards', 'POST /api/job-cards', 'PATCH /api/job-cards'],
    code: ['src/components/screens/Shared.tsx', 'src/app/api/job-cards/route.ts'],
  },
  {
    id: 'people', area: 'Production', title: 'People & CCTV', roles: ['owner'], where: 'Menu → People & CCTV',
    what: 'Per worker: allotted vs done today, efficiency against the target, and active time from station cameras.',
    data: 'workers, efficiency_daily, cctv_activity.',
    rules: ['Efficiency target is set in My firm → Policy.'],
    apis: ['GET /api/workers'],
    code: ['src/components/screens/Owner.tsx'],
    unsure: 'CCTV activity rows come from an external feed / demo data; no camera integration code in this app.',
  },
  // ---------------- Photo reading ----------------
  {
    id: 'capture', area: 'Photo reading', title: 'Capture: read a challan or job card from a photo', roles: ['owner', 'supervisor', 'worker'], where: 'Menu → Capture (worker home)',
    what: 'Take a photo; the app reads it (Google Cloud Vision OCR + fixed rules for the firm\'s printouts; the AI model only when the rules can\'t read it) and fills the entry.',
    data: 'capture_events (read result, confidence, engine, timings); the photo goes to private storage (Supabase) for audit.',
    rules: [
      'Owner: any capture. Supervisor: incoming + outgoing challans. Worker: job card only.',
      'Auto-confirm: a read at or above the firm\'s auto-confirm % (My firm → Policy, 50–100; 100 = always review) is saved straight to the ledger; anything that can\'t be saved stays in the review queue.',
      'Every paid AI / OCR call is logged with its cost (developer console → AI usage & cost).',
    ],
    apis: ['POST /api/capture', 'GET /api/capture', 'GET /api/photos'],
    code: ['src/app/api/capture/route.ts', 'src/lib/vision.ts', 'src/lib/capture/parse.ts', 'src/lib/ai.ts', 'src/lib/photos.ts'],
  },
  {
    id: 'review', area: 'Photo reading', title: 'Review queue (confirm / correct / reject a read)', roles: ['owner', 'supervisor'], where: 'Bell → Review queue tab',
    what: 'Photo reads waiting for a check. Confirm, correct fields, or reject. Confirmed / corrected reads are written to the ledger with the same rules as manual entry.',
    data: 'capture_events → stock_movements / job_cards.',
    rules: ['Supervisors review the challans they capture + job cards from their sections.', 'Review time is recorded (feeds "time saved").'],
    apis: ['POST /api/capture/confirm'],
    code: ['src/components/screens/Shared.tsx', 'src/app/api/capture/confirm/route.ts'],
  },
  {
    id: 'time-saved', area: 'Photo reading', title: 'Time saved', roles: ['owner'], where: 'Overview; Reports',
    what: 'Minutes saved by photo capture vs typing by hand: today, 7 days, 30 days.',
    data: 'capture_events (capture + review seconds) vs the manual baseline (My firm → Policy: minutes per challan / job card).',
    rules: ['Per confirmed read: saved = manual minutes − (photo time + review time), never below 0.', 'Reads with no recorded time count as 60 s (conservative).'],
    apis: ['GET /api/value'],
    code: ['src/lib/value.ts'],
  },
  // ---------------- Sales ----------------
  {
    id: 'inquiries', area: 'Sales', title: 'Inquiries', roles: ['owner', 'supervisor'], where: 'Orders & inquiries → Inquiries',
    what: 'Paste / type a party\'s message ("need 2000 m DON-2 by 10th, rate?", English / Hindi / Gujarati); the app pulls out quality, meters and date, checks free stock and drafts a reply. Status: new → quoted → won / lost; a won inquiry becomes an order (once).',
    data: 'inquiries; free stock from the ledger.',
    rules: ['Selling-rate lists are off: the draft quotes only a rate the owner typed on that inquiry.', 'Supervisors see no rate.', 'Newest first.'],
    apis: ['GET /api/inquiries', 'POST /api/inquiries', 'GET /api/inquiries/[id]', 'PATCH /api/inquiries/[id]', 'POST /api/inquiries/[id]/convert'],
    code: ['src/components/screens/Orders.tsx', 'src/lib/sales/inquiries.ts'],
  },
  {
    id: 'orders', area: 'Sales', title: 'Orders and keeping stock aside', roles: ['owner', 'supervisor'], where: 'Orders & inquiries → Orders',
    what: 'Orders (party, quality, design, meters, rate typed per order, promise date). Status follows what is sent: open → partly dispatched → dispatched, or cancelled. Stock can be kept aside (reserved) for an order: automatically (fewest lots, oldest first) or a chosen lot.',
    data: 'orders, allocations (reservations), stock_movements.order_id (what was sent against the order).',
    rules: [
      'Sent meters = OUT entries linked to the order. An OUT entry without an order doesn\'t count — the Dispatch agent asks the owner (it links by itself only when the lot was kept aside for that order).',
      'Dispatched when ≥ 98% is sent (cloth is rarely cut to the exact meter).',
      'A lot can never have more kept aside than its balance; releasing makes it free again; cancelling an order releases its lots.',
      'Supervisors: meters only, can keep lots aside, can\'t create orders or see rates.',
    ],
    apis: ['GET /api/orders', 'POST /api/orders', 'GET /api/orders/[id]', 'PATCH /api/orders/[id]', 'POST /api/orders/[id]/allocate', 'GET /api/orders/[id]/candidates', 'POST /api/allocations/[id]/release'],
    code: ['src/lib/sales/orders.ts', 'src/lib/sales/allocate.ts', 'src/lib/orderStatus.ts'],
  },
  {
    id: 'dispatch', area: 'Sales', title: 'Dispatch & documents', roles: ['owner', 'supervisor'], where: 'Menu → Dispatch (& documents)',
    what: 'Record a dispatch (party, optional order, lines of lot + meters, transporter, LR no., vehicle, packages) and print the delivery challan and packing list PDFs. "Use reserved lots" fills in the lots kept aside for the order.',
    data: 'dispatches + one OUT stock movement per lot, in one transaction.',
    rules: ['All-or-nothing: any line over its lot balance refuses the whole dispatch.', 'Against an order: updates its status and uses up its reservations on those lots.', 'Credit check warns when the party is over its limit (owner sees ₹, supervisor a neutral warning).', 'Challan / packing list have no rates.'],
    apis: ['GET /api/dispatches', 'POST /api/dispatches', 'GET /api/dispatches/[id]', 'GET /api/docs/challan', 'GET /api/docs/packing-list', 'GET /api/credit/check'],
    code: ['src/components/screens/Dispatch.tsx', 'src/lib/dispatch/dispatches.ts', 'src/lib/pdf'],
  },
  {
    id: 'whatsapp', area: 'Sales', title: 'WhatsApp messages (Meta Cloud API)', roles: ['owner', 'supervisor', 'developer'],
    where: 'My firm → Policy → WhatsApp (owner switches, test); Money → Reminder → Send on WhatsApp; Dispatch list → WhatsApp column; developer console → WhatsApp',
    what: 'Sends three approved templates straight from the firm\'s WhatsApp number: payment reminders (owner taps "Send on WhatsApp", or automatically each morning for bills overdue by N days), a dispatch message to the party when a dispatch is saved (challan, date, lots, qualities, meters, transport — no ₹), and a morning summary to the owner (stock, yesterday in / out, orders due / late, overdue total, alerts). Delivery statuses and messages people send come back through the webhook and are logged. Not connected → everything works as before with wa.me drafts.',
    data: 'whatsapp_settings (switches, template names, language), whatsapp_messages (every message in / out with status, errors, related party / invoices / dispatch), parties.phone (party numbers), users.phone (owner).',
    rules: [
      'Only the owner sends payment reminders (₹); supervisors can only (re)send dispatch messages, which carry no ₹.',
      'One reminder per party per 7 days unless the owner confirms "send another"; the same dispatch / summary is never sent twice (dedupe key), a failed one can be retried.',
      'Recording a dispatch never waits for WhatsApp: the message is logged as queued, and Meta is called after the response with next/server after() (Vercel waitUntil, 10 s timeout), then marked sent / failed. Explicit buttons (Send on WhatsApp, Send again, test) wait for Meta\'s answer so they can show it.',
      'Business-started messages must use Meta-approved templates (Utility); free text is only allowed within 24 h of the party writing — the app sends templates only and does not auto-reply.',
      'Numbers: stored 10-digit → sent as 91XXXXXXXXXX. Parties without a valid mobile are skipped.',
      'The daily job runs with the 07:00 IST cron after the agents; at most 25 automatic reminders per run, stops on a rate-limit error.',
      'Webhook is public but checked: GET verify token, POST X-Hub-Signature-256 (HMAC-SHA256 with the app secret); duplicates and out-of-order statuses are handled.',
    ],
    apis: ['GET /api/whatsapp', 'PUT /api/whatsapp', 'POST /api/whatsapp/test', 'POST /api/whatsapp/reminder', 'POST /api/whatsapp/dispatch', 'GET /api/whatsapp/webhook', 'POST /api/whatsapp/webhook', 'GET /api/dev/whatsapp', 'PUT /api/dev/whatsapp', 'POST /api/dev/whatsapp'],
    code: ['src/lib/whatsapp', 'src/app/api/whatsapp', 'src/app/api/dev/whatsapp/route.ts', 'src/app/dev/WhatsAppPanel.tsx', 'src/components/screens/Policy.tsx'],
    unsure: 'Tested against a fake Graph API server, not against Meta itself; template approval and the live webhook need the real Meta app.',
  },
  // ---------------- Money ----------------
  {
    id: 'invoices', area: 'Money', title: 'GST invoices and Tally', roles: ['owner'], where: 'Dispatch & documents → Invoices',
    what: 'Make a GST invoice from a dispatch, or record one made in Tally; cancel; download PDF; export app-made invoices for Tally (Excel or XML).',
    data: 'invoices (lines, taxes, due date).',
    rules: ['Rate per line: typed on the invoice, else the order\'s rate (no rate list).', 'Same state as the firm → CGST + SGST (half each); otherwise IGST. Never both.', 'Invoice numbers are consecutive per Indian financial year (April–March).', 'Due date = invoice date + party credit days (default 30).', 'One dispatch can\'t be invoiced twice.'],
    apis: ['GET /api/invoices', 'POST /api/invoices', 'GET /api/invoices/[id]', 'PATCH /api/invoices/[id]', 'GET /api/invoices/export', 'GET /api/docs/invoice'],
    code: ['src/lib/dispatch/invoices.ts', 'src/lib/gst.ts', 'src/lib/dispatch/tally.ts'],
  },
  {
    id: 'money', area: 'Money', title: 'Money: Outstanding, Payments, Margin', roles: ['owner'], where: 'Menu → Money',
    what: 'Outstanding per party with ageing (not due, 1–30, 31–60, 61–90, 90+ days), payment reminders (English / Hindi / Gujarati, WhatsApp link), party statement PDF; record payments; margin by party / quality / order / lot.',
    data: 'invoices, payments, parties (credit limit / days).',
    rules: ['Payments settle the oldest unpaid bills first (FIFO): unpaid → part-paid → paid.', 'Outstanding = invoiced − paid; overdue = unpaid on bills past the due date.', 'Margin cost = purchase rate + grey → finished shortage only: process costs are turned off, so margin is overstated.'],
    apis: ['GET /api/credit', 'GET /api/credit/reminder', 'GET /api/payments', 'POST /api/payments', 'GET /api/margin', 'GET /api/docs/statement', 'GET /api/costs/lot'],
    code: ['src/components/screens/Money.tsx', 'src/lib/money/credit.ts', 'src/lib/money/reminder.ts', 'src/lib/money/costing.ts'],
  },
  {
    id: 'rates-off', area: 'Money', title: 'Selling rates and process costs — turned off', roles: ['owner'], where: '(no screen)',
    what: 'At the owner\'s request there is no rate list and no process-cost list: every party gets its own rate, typed on the order or the invoice.',
    data: 'The old rates / process_costs tables and rows stay; nothing reads them.',
    rules: ['POST /api/rates and POST /api/costs answer 410.', 'The Margin agent (costing) is switched off for the same reason.'],
    apis: ['GET /api/rates', 'GET /api/costs', 'GET /api/orders/rate'],
    code: ['src/app/api/rates/route.ts', 'src/app/api/costs/route.ts'],
  },
  // ---------------- Reports ----------------
  {
    id: 'reports', area: 'Reports', title: 'Reports and inventory picture', roles: ['owner'], where: 'Menu → Reports',
    what: 'Day / week / month report: stock in / out, dispatch by party, production and shortage, efficiency, orders, inquiries, money (owner), AI cost (owner), with change vs the previous period and a short written summary; Excel download. Inventory: free stock and days of cover per quality, ageing lots, lots with no location, mill loss.',
    data: 'Fixed queries over the ledger, job cards, orders, invoices, llm_usage.',
    rules: ['Week = Mon–Sun, month = calendar month, both capped at today.', 'The summary is rule-based; with an AI key it is reworded on the low tier (numbers checked).', 'Supervisors get meters only through the API (no Reports menu for them).'],
    apis: ['GET /api/reports', 'GET /api/reports/export', 'GET /api/inventory'],
    code: ['src/components/screens/Reports.tsx', 'src/lib/reports/build.ts', 'src/lib/reports/inventory.ts'],
  },
  // ---------------- Firm & team ----------------
  {
    id: 'my-firm', area: 'Firm & team', title: 'My firm', roles: ['owner'], where: 'Menu → My firm',
    what: 'Five parts: Firm & billing (GST, bank, invoice numbering) · Parties · Markets & locations · Policy (rules, stock alerts, firm knowledge notes) · Team.',
    data: 'app_settings, parties, sections, supervisor_sections, knowledge_docs, users, workers.',
    rules: ['Party names are unique ignoring case and spaces; GSTIN must be valid; credit days default 30.', 'Policy: shortage limit %, efficiency target %, auto-confirm %, manual minutes per challan / job card, low-stock meters, ageing days.', 'Firm knowledge notes are what the chat answers policy / how-to questions from.'],
    apis: ['GET /api/settings', 'PUT /api/settings', 'GET /api/settings/billing', 'PUT /api/settings/billing', 'GET /api/parties', 'POST /api/parties', 'PATCH /api/parties/[id]', 'GET /api/knowledge', 'POST /api/knowledge', 'PATCH /api/knowledge', 'POST /api/settings/sections', 'PATCH /api/settings/sections'],
    code: ['src/components/screens/MyFirm.tsx', 'src/components/screens/MasterData.tsx', 'src/components/screens/Policy.tsx'],
  },
  {
    id: 'team', area: 'Firm & team', title: 'Team, sign ups and removals', roles: ['owner'], where: 'My firm → Team',
    what: 'Sign ups waiting for approval at the top (also in the bell); supervisors (with their sections), workers, everyone who can sign in: switch off, remove, change role, reset password, see / end their devices.',
    data: 'users, workers, auth_sessions, auth_audit.',
    rules: ['Approve with a role: supervisor → sections; worker → an existing worker record or a section.', 'Removing someone: they disappear from every list and picker and are signed out at once, but old records (job cards, challans) keep their name; their phone number can be used again. The owner can\'t be removed.', 'Switching off, role change, password reset and rejection sign the person out everywhere.'],
    apis: ['GET /api/users', 'GET /api/users/[id]', 'POST /api/users/[id]', 'POST /api/settings/users', 'PATCH /api/settings/users', 'GET /api/workers', 'POST /api/workers', 'PATCH /api/workers', 'DELETE /api/workers'],
    code: ['src/components/screens/Team.tsx', 'src/app/api/users/[id]/route.ts'],
  },
  {
    id: 'settings', area: 'Firm & team', title: 'Settings', roles: ['owner', 'supervisor', 'worker'], where: 'Menu → Settings',
    what: 'Only things about you and this device: account (change password, sign out), preferences (theme, language; density for the owner), and for the owner a yes/no "what works right now" (photo reading, AI writing).',
    data: 'Browser storage for preferences; /api/status.',
    rules: ['Firm things live in My firm.'],
    apis: ['GET /api/status', 'POST /api/auth/password'],
    code: ['src/components/screens/Settings.tsx', 'src/components/screens/Account.tsx'],
  },
  // ---------------- Access & sign-in ----------------
  {
    id: 'signin', area: 'Access & sign-in', title: 'Sign in, sign up, sessions', roles: ['owner', 'supervisor', 'worker', 'developer'], where: '/ (clients), /dev/login (developer)',
    what: 'Clients sign in with a 10-digit mobile number + password; anyone can sign up as supervisor / worker and waits for the owner\'s approval. Developers sign in with email + password (no sign up).',
    data: 'users, auth_sessions (hashed tokens), auth_audit.',
    rules: ['Passwords stored only as hashes; 8–128 characters; easy ones refused when a person chooses one.', 'Created / reset accounts get a one-time starting password; they must change it first.', '5 wrong passwords in 15 minutes pause that login for 15 minutes.', 'Access cookie 15 min, refreshed from an HttpOnly refresh cookie (sent only to /api/auth); client sessions 60 days sliding, developer 12 hours. Re-using an old refresh token after 30 s ends the session.', 'A rejected number may sign up again up to 3 times.'],
    apis: ['POST /api/auth/login', 'POST /api/auth/signup', 'POST /api/auth/refresh', 'POST /api/auth/logout', 'GET /api/auth/me', 'POST /api/auth/password', 'POST /api/auth/dev/login'],
    code: ['src/lib/auth', 'src/lib/apiAuth.ts', 'src/proxy.ts'],
    unsure: 'src/proxy.ts (Next 16 middleware) path not re-checked this round.',
  },
  {
    id: 'access', area: 'Access & sign-in', title: 'Who sees what (roles and capability switches)', roles: ['developer'], where: 'Developer console → Access & roles',
    what: 'The matrix of capabilities per role. The developer can switch a capability off (and back on) for supervisors or workers; their menus hide it and the APIs refuse it within about 30 seconds.',
    data: 'app_settings.access_overrides; the matrix is in code (src/lib/access.ts).',
    rules: ['Never more than the role has by default; the owner is always full access.', 'Some are locked "always on" (a worker\'s capture).', 'Every API route must call requireUser / requireCap / requireRole / requireDeveloper (scripts/check-route-auth.js checks it).', 'Supervisors never receive ₹ values; workers can\'t use orders, dispatch, money or reports.'],
    apis: ['GET /api/dev/access', 'PUT /api/dev/access'],
    code: ['src/lib/access.ts', 'src/lib/apiAuth.ts', 'src/app/api/dev/access/route.ts'],
  },
  // ---------------- Assistant ----------------
  {
    id: 'chat', area: 'Assistant', title: 'Chat and voice', roles: ['owner', 'supervisor'], where: 'Chat button (desktop bottom-right; phone top bar)',
    what: 'Ask questions in plain words ("how many workers", "dispatch by party this month", "what is our return policy"); dictate or use hands-free voice mode (answers out loud in English / Hindi / Gujarati).',
    data: 'Fixed query templates and a semantic layer over the ledger; firm knowledge notes for policy questions.',
    rules: ['The AI never writes SQL and never sees the database: it only picks a template / metric, or answers from the firm\'s notes.', 'Supervisors get no ₹ figures.', 'Voice-to-text on phones without built-in speech recognition uses the low AI tier (logged).'],
    apis: ['POST /api/chat', 'POST /api/chat/transcribe'],
    code: ['src/components/ChatDock.tsx', 'src/lib/chat/router.ts'],
  },
  // ---------------- Developer ----------------
  {
    id: 'dev-console', area: 'Developer', title: 'Developer console', roles: ['developer'], where: '/dev',
    what: 'Health (services, connections, tables, migrations) · AI usage & cost · Errors · Users & view as · Access & roles · Audit trail · Agents · Docs.',
    data: 'llm_usage, app_errors, auth_audit, users, agent_settings, agent_runs, agent_suggestions, schema_migrations.',
    rules: ['/api/dev/* answers 404 to anyone who is not a signed-in developer.', '"View as" is read-only unless DEV_VIEW_AS_WRITE=1; every start / stop and every API call while viewing is audited.', 'Only the developer creates the owner account.'],
    apis: ['GET /api/dev/health', 'GET /api/dev/usage', 'GET /api/dev/errors', 'GET /api/dev/users', 'POST /api/dev/users', 'POST /api/dev/view-as', 'DELETE /api/dev/view-as', 'GET /api/dev/audit', 'GET /api/dev/agents', 'PUT /api/dev/agents', 'POST /api/dev/agents', 'GET /api/dev/docs'],
    code: ['src/app/dev/page.tsx', 'src/app/api/dev'],
  },
  {
    id: 'agents', area: 'Developer', title: 'Agents (helpers that raise cards)', roles: ['owner', 'supervisor', 'developer'], where: 'Cards in the bell / Overview / Floor; developer console → Agents',
    what: 'Deterministic checks (no AI) that look at orders, stock, dispatches, invoices and payments and raise a card with one button when something needs a person. See the Agents tab for each one.',
    data: 'agent_suggestions (cards), agent_settings (on/off), agent_runs (run log).',
    rules: ['Cards are never duplicated (one per real-world problem) and close themselves when the problem goes away.', 'Dismissed cards stay quiet for the kind\'s quiet days.', 'At most N cards per agent are shown (default 8).', 'Scans run in the background: the attention list never waits for them.'],
    apis: ['GET /api/agents/suggestions', 'POST /api/agents/suggestions', 'GET /api/agents/run', 'POST /api/agents/run'],
    code: ['src/lib/agents'],
  },
];

export interface DocApi { path: string; methods: string; who: string; what: string }

/** Every API route (method → who may call it → what it does). The Docs tab flags routes found on disk but missing here. */
export const APIS: DocApi[] = [
  { path: '/api/agents/run', methods: 'GET · POST', who: 'GET: Vercel cron (CRON_SECRET) · POST: owner', what: 'Run every agent\'s scan now.' },
  { path: '/api/agents/suggestions', methods: 'GET · POST', who: 'owner, supervisor (no money cards); workers get none', what: 'List open cards (fast; starts a background scan when due) · accept / dismiss a card.' },
  { path: '/api/allocations/[id]/release', methods: 'POST', who: 'owner, supervisor', what: 'Release one reservation.' },
  { path: '/api/auth/dev/login', methods: 'POST', who: 'public', what: 'Developer sign-in (email + password).' },
  { path: '/api/auth/login', methods: 'POST', who: 'public', what: 'Client sign-in (phone + password).' },
  { path: '/api/auth/logout', methods: 'POST', who: 'public', what: 'End this device\'s session.' },
  { path: '/api/auth/me', methods: 'GET', who: 'public (401 without a session)', what: 'Who is signed in.' },
  { path: '/api/auth/password', methods: 'POST', who: 'any signed-in user', what: 'Change password; signs out other devices.' },
  { path: '/api/auth/refresh', methods: 'POST', who: 'public (refresh cookie)', what: 'New access + refresh token (rotation).' },
  { path: '/api/auth/signup', methods: 'POST', who: 'public', what: 'Pending account until the owner approves.' },
  { path: '/api/capture', methods: 'GET · POST', who: 'signed in (by capture rights)', what: 'Read a photo (OCR / rules / AI), auto-confirm above the %; list reads.' },
  { path: '/api/capture/confirm', methods: 'POST', who: 'owner, supervisor', what: 'Confirm / correct / reject a read (writes the ledger).' },
  { path: '/api/chat', methods: 'POST', who: 'owner, supervisor', what: 'Answer a question from templates or firm notes.' },
  { path: '/api/chat/transcribe', methods: 'POST', who: 'owner, supervisor', what: 'Speech → text (low AI tier).' },
  { path: '/api/costs', methods: 'GET · POST', who: 'owner', what: 'Old process-cost list (read-only); POST → 410 (turned off).' },
  { path: '/api/costs/lot', methods: 'GET', who: 'owner', what: 'Cost ₹/m of one lot.' },
  { path: '/api/credit', methods: 'GET', who: 'owner', what: 'Outstanding, overdue, ageing per party.' },
  { path: '/api/credit/check', methods: 'GET', who: 'owner, supervisor (no ₹)', what: 'Would this amount take the party over its limit?' },
  { path: '/api/credit/reminder', methods: 'GET', who: 'owner', what: 'Payment reminder text + WhatsApp link (en / hi / gu) + WhatsApp Cloud API state (connected, number, last reminder status).' },
  { path: '/api/db-check', methods: 'GET', who: 'developer', what: 'Table counts.' },
  { path: '/api/dev/access', methods: 'GET · PUT', who: 'developer', what: 'Capability matrix; switch a capability off / on for a role.' },
  { path: '/api/dev/agents', methods: 'GET · PUT · POST', who: 'developer', what: 'Agents: status + stats · switch on/off, max cards · run now.' },
  { path: '/api/dev/audit', methods: 'GET', who: 'developer', what: 'Audit trail.' },
  { path: '/api/dev/docs', methods: 'GET', who: 'developer', what: 'Live parts of the Docs tab: migrations applied, env vars set / not set, routes on disk.' },
  { path: '/api/dev/errors', methods: 'GET', who: 'developer', what: 'Technical errors logged by the server.' },
  { path: '/api/dev/health', methods: 'GET', who: 'developer', what: 'Services, database, migrations, connections.' },
  { path: '/api/dev/usage', methods: 'GET', who: 'developer', what: 'AI usage and cost.' },
  { path: '/api/dev/users', methods: 'GET · POST', who: 'developer', what: 'Accounts; set up the owner; reset passwords; end sessions.' },
  { path: '/api/dev/whatsapp', methods: 'GET · PUT · POST', who: 'developer', what: 'WhatsApp: connection check, env vars set / not set, webhook URL, templates, message log, counts by day · template names / language · run the daily WhatsApp job now.' },
  { path: '/api/dev/view-as', methods: 'POST · DELETE', who: 'developer', what: 'Start / stop viewing the app as a user (read-only by default).' },
  { path: '/api/dispatches', methods: 'GET · POST', who: 'owner, supervisor', what: 'List / record dispatches (+ optional invoice for the owner).' },
  { path: '/api/dispatches/[id]', methods: 'GET', who: 'owner, supervisor', what: 'One dispatch with its lines.' },
  { path: '/api/docs/challan', methods: 'GET', who: 'owner, supervisor', what: 'Delivery challan PDF (no rates).' },
  { path: '/api/docs/invoice', methods: 'GET', who: 'owner', what: 'GST invoice PDF.' },
  { path: '/api/docs/packing-list', methods: 'GET', who: 'owner, supervisor', what: 'Packing list PDF.' },
  { path: '/api/docs/statement', methods: 'GET', who: 'owner', what: 'Party statement PDF (or JSON).' },
  { path: '/api/inquiries', methods: 'GET · POST', who: 'owner, supervisor', what: 'List / log inquiries (reads the text, checks stock, drafts a reply).' },
  { path: '/api/inquiries/[id]', methods: 'GET · PATCH', who: 'owner, supervisor', what: 'One inquiry; change status / fields.' },
  { path: '/api/inquiries/[id]/convert', methods: 'POST', who: 'owner', what: 'Won inquiry → order (once).' },
  { path: '/api/inventory', methods: 'GET', who: 'owner, supervisor', what: 'Inventory picture (meters only).' },
  { path: '/api/invoices', methods: 'GET · POST', who: 'owner', what: 'List invoices / make or record one.' },
  { path: '/api/invoices/[id]', methods: 'GET · PATCH', who: 'owner', what: 'One invoice; cancel.' },
  { path: '/api/invoices/export', methods: 'GET', who: 'owner', what: 'Tally export (xlsx / xml).' },
  { path: '/api/job-cards', methods: 'GET · POST · PATCH', who: 'owner, supervisor (workers: own cards, read)', what: 'Job cards and allotments.' },
  { path: '/api/knowledge', methods: 'GET · POST · PATCH', who: 'owner', what: 'Firm knowledge notes for the chat.' },
  { path: '/api/lots/location', methods: 'GET · POST', who: 'owner, supervisor', what: 'Lot location history; move a lot.' },
  { path: '/api/lots', methods: 'GET', who: 'owner, supervisor', what: 'Lots & balance, filtered and paged (counts capped at 10,000+).' },
  { path: '/api/lots/search', methods: 'GET', who: 'owner, supervisor', what: 'Lot type-ahead (number prefix, then quality / design / location); ids= for a few known lots.' },
  { path: '/api/overview', methods: 'GET', who: 'owner, supervisor (₹ owner only)', what: 'Home-screen figures: open / late / due orders, outstanding and overdue (round 3, engineer D).' },
  { path: '/api/search', methods: 'GET', who: 'signed in (only what the role may see; workers nothing)', what: 'Global search across lots, orders, inquiries, dispatches, parties, people (round 3, engineer B).' },
  { path: '/api/search/lot', methods: 'GET', who: 'owner, supervisor', what: 'Lot card for the search box: lot, moves, job cards (meters only).' },
  { path: '/api/margin', methods: 'GET', who: 'owner', what: 'Margin by order / party / quality / lot.' },
  { path: '/api/orders', methods: 'GET · POST', who: 'GET owner, supervisor · POST owner', what: 'List / create orders.' },
  { path: '/api/orders/[id]', methods: 'GET · PATCH', who: 'GET owner, supervisor · PATCH owner', what: 'One order with reservations; edit / cancel.' },
  { path: '/api/orders/[id]/allocate', methods: 'POST', who: 'owner, supervisor', what: 'Keep stock aside (auto or a chosen lot).' },
  { path: '/api/orders/[id]/candidates', methods: 'GET', who: 'owner, supervisor', what: 'Lots that could fill the order.' },
  { path: '/api/orders/rate', methods: 'GET', who: 'owner', what: 'Always { rate: null } (rate lists are off).' },
  { path: '/api/parties', methods: 'GET · POST', who: 'GET owner, supervisor (names only) · POST owner', what: 'Parties (clients).' },
  { path: '/api/parties/[id]', methods: 'PATCH', who: 'owner', what: 'Edit a party.' },
  { path: '/api/payments', methods: 'GET · POST', who: 'owner', what: 'Payments; settles oldest bills first.' },
  { path: '/api/photos', methods: 'GET', who: 'signed in', what: 'Short-lived link to a stored photo.' },
  { path: '/api/rates', methods: 'GET · POST', who: 'owner', what: 'Old rate list (read-only); POST → 410 (turned off).' },
  { path: '/api/reports', methods: 'GET', who: 'owner, supervisor (meters only)', what: 'Day / week / month report.' },
  { path: '/api/reports/export', methods: 'GET', who: 'owner, supervisor', what: 'Report as Excel.' },
  { path: '/api/settings', methods: 'GET · PUT', who: 'GET any signed-in · PUT owner', what: 'Firm configuration, rules, locations, markets.' },
  { path: '/api/settings/billing', methods: 'GET · PUT', who: 'owner', what: 'GST / bank / invoice numbering + stock-alert thresholds.' },
  { path: '/api/settings/sections', methods: 'POST · PATCH', who: 'owner', what: 'Add / rename / switch sections.' },
  { path: '/api/settings/users', methods: 'POST · PATCH', who: 'owner', what: 'Supervisors and the owner profile.' },
  { path: '/api/status', methods: 'GET', who: 'signed in', what: 'Yes / no: photo reading, AI writing.' },
  { path: '/api/stock', methods: 'GET · POST', who: 'GET owner, supervisor · POST owner', what: 'Stock summary, today, 7-day flow, known names; manual IN / OUT entry.' },
  { path: '/api/stock/edit', methods: 'GET · PATCH', who: 'owner', what: 'Ledger edit mode (and its edit log).' },
  { path: '/api/stock/export', methods: 'GET', who: 'owner', what: 'Challans or lot balances as Excel; blank templates: kind=template (app), incoming_template, outgoing_template (the firm\'s registers).' },
  { path: '/api/stock/flow', methods: 'GET', who: 'owner, supervisor', what: 'Stock in / out over a period.' },
  { path: '/api/stock/import', methods: 'POST', who: 'owner', what: 'Excel import step 1: check only.' },
  { path: '/api/stock/import/commit', methods: 'POST', who: 'owner', what: 'Excel import step 2: save a chunk.' },
  { path: '/api/stock/import/fix', methods: 'POST', who: 'owner', what: 'Excel import: the skipped rows as a "Rows to fix" .xlsx (built from what the check returned).' },
  { path: '/api/stock/ledger', methods: 'GET', who: 'owner, supervisor', what: 'Ledger rows, filtered and paged.' },
  { path: '/api/stock/next-sr', methods: 'GET', who: 'owner', what: 'Next free SR no. per direction.' },
  { path: '/api/users', methods: 'GET', who: 'owner', what: 'Everyone who can sign in (pending first).' },
  { path: '/api/users/[id]', methods: 'GET · POST', who: 'owner', what: 'Devices; approve / reject / switch off / role / sections / phone / reset / sign out.' },
  { path: '/api/value', methods: 'GET', who: 'signed in', what: 'Time saved by photo capture.' },
  { path: '/api/whatsapp', methods: 'GET · PUT', who: 'owner', what: 'WhatsApp switches (auto reminders + days, dispatch messages, morning summary + extra numbers), connected or not, last messages received.' },
  { path: '/api/whatsapp/dispatch', methods: 'POST', who: 'owner, supervisor', what: 'Send the dispatch message to the party again (no ₹).' },
  { path: '/api/whatsapp/reminder', methods: 'POST', who: 'owner', what: 'Send the payment reminder template now (once per 7 days unless force).' },
  { path: '/api/whatsapp/test', methods: 'POST', who: 'owner', what: 'Test message to the owner (summary template, else Meta hello_world).' },
  { path: '/api/whatsapp/webhook', methods: 'GET · POST', who: 'public — Meta only (verify token / X-Hub-Signature-256)', what: 'Webhook: verification, message statuses, incoming messages (logged).' },
  { path: '/api/workers', methods: 'GET · POST · PATCH · DELETE', who: 'GET signed in (worker: self) · others owner', what: 'Workers, efficiency, CCTV.' },
];

export interface DocMigration { name: string; what: string }
export const MIGRATIONS: DocMigration[] = [
  { name: '000_base_schema.sql', what: 'Users, workers, lots, capture events, stock movements, job cards, allotments, efficiency, CCTV, chat audit.' },
  { name: '001_incoming_fields_and_lot_location.sql', what: 'Grey / finished meters, mill / weaver on IN entries; lot location history.' },
  { name: '002_firm_settings.sql', what: 'app_settings (firm, rules), sections, supervisor sections.' },
  { name: '003_setup_narmada_group.sql', what: 'The client firm\'s initial setup.' },
  { name: '004_decision_layer_usage_value.sql', what: 'AI usage log (llm_usage), firm knowledge notes, time-saved fields.' },
  { name: '005_phase2_agents.sql', what: 'Parties, rates, process costs, inquiries, orders, allocations, dispatches, invoices, payments, agent_suggestions, generated docs.' },
  { name: '006_auth.sql', what: 'Sign-in: passwords, sessions, audit trail, error log.' },
  { name: '007_stock_fields_markets.sql', what: 'SR no., pieces, import ref; markets.' },
  { name: '008_sections_folding_packing.sql', what: 'Only Folding and Packing sections in use.' },
  { name: '009_ledger_edits_access_delete.sql', what: 'Ledger edit log, removed team members (deleted_at), capability switches.' },
  { name: '010_stock_state_and_search.sql', what: 'Round 3 (engineer A): kept-up-to-date lot balances and ledger search.' },
  { name: '011_agent_settings.sql', what: 'Round 3: agent on/off + settings (agent_settings), run log (agent_runs), Margin agent off by default.' },
  { name: '013_registers.sql', what: 'The firm\'s registers: stock_movements.kind (normal | adjustment), register_pct, takes (S-1…S-10), loc_code (IN); bill_pct (L), billed_meters (NQTY), lot_status_code (LOT S), linked_sr (OUT); lots.reg_lot_no, lots.loc_code. search_doc also holds loc_code, linked_sr, LOT S. Balance triggers unchanged (adjustments are OUT).' },
  { name: '012_whatsapp.sql', what: 'WhatsApp: whatsapp_settings (owner switches, template names, language) and whatsapp_messages (log of every message in / out with status). Party numbers reuse parties.phone.' },
];

export interface DocCron { path: string; schedule: string; ist: string; what: string; auth: string }
export const CRONS: DocCron[] = [
  { path: '/api/agents/run', schedule: '30 1 * * *', ist: 'Daily 07:00 IST', what: 'Runs every switched-on agent (morning report card, overdue payments, late orders …), then the daily WhatsApp job (morning summary, automatic payment reminders) when the owner switched them on.', auth: 'Header Authorization: Bearer $CRON_SECRET (Vercel sends it). Without CRON_SECRET the route only works outside Vercel.' },
];

export interface DocEnv { name: string; purpose: string; need: 'required' | 'recommended' | 'optional'; secret: boolean }
export const ENV_VARS: DocEnv[] = [
  { name: 'DATABASE_URL', purpose: 'Postgres connection (or POSTGRES_URL on Vercel).', need: 'required', secret: true },
  { name: 'POSTGRES_URL', purpose: 'Alternative name for the database connection (Vercel Postgres / Supabase).', need: 'optional', secret: true },
  { name: 'MIGRATION_DATABASE_URL', purpose: 'Direct (non-pooled) connection for migrations at build time (or POSTGRES_URL_NON_POOLING).', need: 'recommended', secret: true },
  { name: 'POSTGRES_URL_NON_POOLING', purpose: 'Alternative name for the migrations connection.', need: 'optional', secret: true },
  { name: 'SKIP_DB_MIGRATIONS', purpose: '1 = don\'t run migrations during build.', need: 'optional', secret: false },
  { name: 'CRON_SECRET', purpose: 'Protects the daily agents cron (/api/agents/run).', need: 'required', secret: true },
  { name: 'WHATSAPP_TOKEN', purpose: 'WhatsApp Cloud API: permanent System User token (whatsapp_business_messaging). Without it (and the phone number ID) nothing is sent and wa.me drafts are used.', need: 'optional', secret: true },
  { name: 'WHATSAPP_PHONE_NUMBER_ID', purpose: 'WhatsApp Cloud API: the sending number\'s Phone number ID (API Setup).', need: 'optional', secret: false },
  { name: 'WHATSAPP_APP_SECRET', purpose: 'Meta app secret: checks webhook signatures (X-Hub-Signature-256). Webhook calls are refused without it.', need: 'optional', secret: true },
  { name: 'WHATSAPP_VERIFY_TOKEN', purpose: 'Text you choose; Meta sends it when you save the webhook URL.', need: 'optional', secret: true },
  { name: 'WHATSAPP_API_VERSION', purpose: 'Graph API version (default v26.0).', need: 'optional', secret: false },
  { name: 'WHATSAPP_API_BASE', purpose: 'Graph API base URL (default https://graph.facebook.com); tests point it to a fake server.', need: 'optional', secret: false },
  { name: 'GEMINI_API_KEY', purpose: 'AI (reading hard photos, inquiry text, chat routing, wording polish). Without it the app uses rules only.', need: 'recommended', secret: true },
  { name: 'GOOGLE_API_KEY', purpose: 'Fallback name for the Gemini key.', need: 'optional', secret: true },
  { name: 'GEMINI_MODEL_LOW', purpose: 'Low-tier model name (cheap calls).', need: 'optional', secret: false },
  { name: 'GEMINI_MODEL_HIGH', purpose: 'High-tier model name (hard photo reads).', need: 'optional', secret: false },
  { name: 'GEMINI_MODEL', purpose: 'Older single model setting.', need: 'optional', secret: false },
  { name: 'GOOGLE_VISION_API_KEY', purpose: 'OCR for photo reading (the default, cheapest reader).', need: 'recommended', secret: true },
  { name: 'OCR_MIN_CONFIDENCE', purpose: 'OCR confidence below which the AI reader is tried.', need: 'optional', secret: false },
  { name: 'SUPABASE_URL', purpose: 'Photo storage (private bucket) — with SUPABASE_SECRET_KEY.', need: 'recommended', secret: false },
  { name: 'SUPABASE_SECRET_KEY', purpose: 'Photo storage key (or SUPABASE_SERVICE_ROLE_KEY).', need: 'recommended', secret: true },
  { name: 'SUPABASE_SERVICE_ROLE_KEY', purpose: 'Older name for the storage key.', need: 'optional', secret: true },
  { name: 'NEXT_PUBLIC_SUPABASE_URL', purpose: 'Fallback name for the Supabase URL.', need: 'optional', secret: false },
  { name: 'PHOTO_BUCKET', purpose: 'Storage bucket name (default capture-photos).', need: 'optional', secret: false },
  { name: 'DEV_ADMIN_EMAIL', purpose: 'Developer account created at start-up (with DEV_ADMIN_PASSWORD).', need: 'recommended', secret: false },
  { name: 'DEV_ADMIN_PASSWORD', purpose: 'Developer account password.', need: 'recommended', secret: true },
  { name: 'DEV_ADMIN_NAME', purpose: 'Developer account display name.', need: 'optional', secret: false },
  { name: 'DEV_VIEW_AS_WRITE', purpose: '1 = "View as" may write (default read-only).', need: 'optional', secret: false },
  { name: 'AUTH_COOKIE_SECURE', purpose: '1 = Secure cookies outside production.', need: 'optional', secret: false },
  { name: 'AUTH_ACCESS_MINUTES', purpose: 'Access token minutes (default 15).', need: 'optional', secret: false },
  { name: 'AUTH_CLIENT_SESSION_DAYS', purpose: 'Client session days (default 60).', need: 'optional', secret: false },
  { name: 'AUTH_DEVELOPER_SESSION_HOURS', purpose: 'Developer session hours (default 12).', need: 'optional', secret: false },
  { name: 'ALLOW_DEMO_SEED', purpose: '1 = allow the demo data scripts to run.', need: 'optional', secret: false },
  { name: 'ALLOW_MOCK_AI', purpose: '1 = fake AI answers for tests (never in production).', need: 'optional', secret: false },
  { name: 'DB_QUIET', purpose: '1 = don\'t log every SQL query.', need: 'optional', secret: false },
  { name: 'VERCEL / VERCEL_REGION / VERCEL_GIT_COMMIT_SHA', purpose: 'Set by Vercel; shown in Health.', need: 'optional', secret: false },
];

/** Open questions about the firm's registers — short form of docs/AMBIGUOUS.md (the full text, with examples, is there). */
export interface DocQuestion { topic: string; see: string; now: string; ask: string }
export const OPEN_QUESTIONS: DocQuestion[] = [
  { topic: 'LOT S codes (R / E / S / A)', see: 'Per SR.NO, in bill order, always S → R … → E; A only on single big rows.', now: 'Stored and shown; tooltip guess S = start, R = running, E = end, A = all at once. Never changes balances.', ask: 'Is the guess right? Should the app warn when E leaves stock?' },
  { topic: '"L" (sales register)', see: '97–115; NQTY = QTY × L ÷ 100 on every row; per bill, not per quality.', now: 'Stored as bill_pct; NQTY as billed_meters; QTY comes out of stock.', ask: 'What is L? Which meters really left: QTY or NQTY?' },
  { topic: '"%" (incoming register)', see: '2.69–15.81, always inside the % band in the ITEM name.', now: 'Stored as register_pct, shown only.', ask: 'Shrinkage, weight %, …? Should it convert grey ↔ finished?' },
  { topic: 'LOCATION codes', see: '212, "142+143", "56+57+l"; heading spelled LOCTION.', now: 'Stored as written (movement + lot), searchable; imported lots get no app location (Dispatched when finished).', ask: 'Which market + shop are these (shop / rack / pipe numbers)? Map them to market locations like "LM 212"?' },
  { topic: 'MILL codes', see: 'L, D, D42", H.', now: 'Stored as the mill name.', ask: 'Full mill names; is 42" a width?' },
  { topic: 'Two lots in one row', see: 'LOT "172+173", SR.NO "146+204" (4 rows).', now: 'Skipped with a warning → rows to fix.', ask: 'How were meters split? One row per lot possible?' },
  { topic: 'Empty bill rows', see: 'Bills 2189, 2211: only DATE + BNO; bill numbers 2182–2215 continuous.', now: 'Skipped with a warning.', ask: 'Cancelled bills? Record them?' },
  { topic: 'Lot numbers repeat', see: 'Short mill lot numbers (34, 627) can repeat across mills.', now: 'Lot key = LOT NO, else "<LOT NO>-SR<SRNO>"; sales find lots by SR.NO.', ask: 'Is SRNO one continuous series (sales file points at SR 102–571, incoming file has 1–23)?' },
  { topic: 'MTR grey or finished', see: 'One meters column.', now: 'Stock meters only; grey / finished empty.', ask: 'Which is it?' },
  { topic: 'S-1…S-10 more than MTR', see: '15 of 16 finished lots took out 1–6 % more than MTR.', now: 'Balance from STOCK; the extra is noted, not recorded.', ask: 'Stretch / gain, or are S values billed meters (NQTY)?' },
  { topic: 'Same sale counted twice?', see: 'S-n look like the sales also in the Outgoing register.', now: 'Incoming sets balance = STOCK; outgoing then deducts (skipped when stock is short).', ask: 'Use a cut-off date: import incoming once, then only later sales?' },
  { topic: 'Future dates', see: 'SR 9 19-11-2026, SR 12 25-12-2026 among Jan–May rows; sales file "19-8" dated 17-08.', now: 'Saved as written + warning.', ask: 'Typing mistakes (2025)? Refuse instead of warn?' },
  { topic: 'No party in sales', see: 'Only the bill number.', now: 'Imported sales have no party.', ask: 'Add a party column, or look it up by bill no.?' },
  { topic: 'Quality names differ', see: 'Incoming "SOFIYA - 5 % - 10 %" vs sales "SOFIYA".', now: 'Saved on the SR\'s lot with a warning.', ask: 'Same quality? Master list?' },
];
